### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by ibenmiller** [SBoudrias/generator-jest#24]
Errors: 
node-pre-gyp ERR! Tried to download(undefined): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.2/fse-v1.1.2-node-v59-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.1.2 and node@9.2.0 (node-v59 ABI) (falling back to source compile with node-gyp) 

steps:
1. added to package.json
  "devDependencies": {
    "yo": "^2.0.0",
    "generator-jest": "^1.5.0"
  },
2. npm install
3. error occurred

**Comment by ibenmiller** [comment]
BTW, tried to resolve the uri, 'https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.2/fse-v1.1.2-node-v59-darwin-x64.tar.gz', in chrome.  The response is 'The specified key does not exist.'.

Version 1.1.3 does work though.  (https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.2/fse-v1.1.2-node-v59-darwin-x64.tar.gz)

**Comment by SBoudrias** [comment]
Hey, that's either a npm issue or a node-gyp issue. I can't really do anything about that on generator-jest side 😞

**Comment by ibenmiller** [comment]
npm -no-optional fixed the issue. 

Really appreciate you looking into this. 

Gracias,

Benjamin Miller
(954) 830-8496

On Jan 24, 2018, at 10:30 PM, Simon Boudrias <notifications@github.com> wrote:

Closed #24.
